#!/bin/bash

if [ -f .rubocop.yml ] && \
   [ ! $(git diff --name-only --cached --diff-filter=ABCMRTUX | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached --diff-filter=ABCMRTUX | xargs bundle exec rubocop -RED )
then
  cat <<MSG

Rubocop offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .haml-lint.yml ] && \
   [ ! $(git diff --name-only --cached --diff-filter=ABCMRTUX | grep .haml$ | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached --diff-filter=ABCMRTUX | grep .haml$ | xargs bundle exec haml-lint )
then
  cat <<MSG

HAML-lint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .scss-lint.yml ] && \
   [ ! $(git diff --name-only --cached --diff-filter=ABCMRTUX | grep .scss$ | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached --diff-filter=ABCMRTUX | grep .scss$ | xargs bundle exec scss-lint )
then
  cat <<MSG
SCSS-lint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .eslintrc.yml ] && \
   [ ! $(git diff --name-only --cached --diff-filter=ABCMRTUX | grep .js$ | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached --diff-filter=ABCMRTUX | grep .js$ | xargs yarn run eslint )
then
  cat <<MSG
ESLint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi
