#!/bin/bash

if [ -f .rubocop.yml ] && \
   [ ! $(git diff --name-only --cached | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached | xargs bundle exec rubocop -RED )
then
  cat <<MSG

Rubocop offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .haml-lint.yml ] && \
   [ ! $(git diff --name-only --cached ./app | grep .haml | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached ./app | grep .haml | xargs bundle exec haml-lint )
then
  cat <<MSG

HAML-lint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .scss-lint.yml ] && \
   [ ! $(git diff --name-only --cached ./app | grep .scss | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached ./app | grep .scss | xargs bundle exec scss-lint )
then
  cat <<MSG
SCSS-lint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi

if [ -f .eslintrc.yml ] && \
   [ ! $(git diff --name-only --cached | grep .js | wc -l) = 0 ] && \
   ! ( git diff --name-only --cached | grep .js | xargs yarn run eslint )
then
  cat <<MSG
ESLint offences were found, the commit was aborted.
If you really want to commit anyway run:
  git commit --no-verify
MSG
  exit 1
fi
